// Generated by CoffeeScript 1.4.0
(function() {

  chai.should();

  describe('TLog class', function() {
    it('should be visible, have the global logs collection and log http by default', function() {
      TLog.should.exist;
      TLog._global_logs.should.exist;
      return TLog._log_http.should.be["true"];
    });
    return it('should return the default logger and create the logs collection', function() {
      var tl;
      tl = TLog.getLogger();
      return tl.should.exist;
    });
  });

}).call(this);
